### ISSUE TITLE
코드 수정 요청 사항

### ISSUE THREAD

**Issue by snoopspy** [Yum-Github/add_nbo#1]
https://github.com/Yum-Github/add_nbo/commit/87a92bb07dc93af15d7aa8d085d11054d3bd138b#r38121678

https://github.com/Yum-Github/add_nbo/commit/3ffe1ce1fa9a6b3e14c581ecfc25ac9ffcd7ff82#r38121689

**Comment by Yum-Github** [comment]
done in https://github.com/Yum-Github/add_nbo/commit/895b1beffab3c0d8c1c02cd8f71b556e1f34405f

**Comment by snoopspy** [comment]
수고하셨습니다.
